export const colors = {
    light: {
        background: '#F0F4F8',
        backgroundSecondary: '#FFFFFF',
        text: '#1F2937',
        textSecondary: '#6B7280',
        accent: '#1F2937',
        accentText: '#FFFFFF',
        border: '#E5E7EB',
        decorative1: '#FFE5D9',
        decorative2: '#E3F2FD',
        decorative3: '#E8F5E9',
        input: '#F5F7FA',
        inputBorder: '#E5E7EB',
        error: '#FEE2E2',
        errorText: '#DC2626',
        success: '#D1FAE5',
        successText: '#059669',
    },
    dark: {
        background: '#28443f',
        backgroundSecondary: '#28443f',
        text: '#F2FD7D',
        textSecondary: '#D1D5DB',
        accent: '#F2FD7D',
        accentText: '#28443f',
        border: '#F2FD7D',
        decorative1: '#F2FD7D',
        decorative2: '#F2FD7D',
        decorative3: '#F2FD7D',
        input: '#1a2a27',
        inputBorder: '#F2FD7D',
        error: '#7F1D1D',
        errorText: '#FCA5A5',
        success: '#14532D',
        successText: '#86EFAC',
    },
};

export const getColors = (isDark: boolean) => isDark ? colors.dark : colors.light;
